### ISSUE TITLE
bundling gnulib into release tarballs

### ISSUE THREAD

**Issue by morfoh** [luaposix/luaposix#106]
Hi,

I really wonder why gnulib is not bundled within release tarballs, besides the obvious question why luaposix is relying on gnulib anyway - but that is a different topic. The thing that bothers me more is why you are relying on cloning a remote git repository before being able to build from a release tarball? Why aren't you bundling gnulib within release tarballs, like 99.99999% of other projects that rely on that infamous piece of bloat and redundancy?

Here are some points to think about:
1. I think it is not quite uncommon that automatized build environments are building stuff within a chroot sandbox which has no network connectivity.
2. building from a release tarball also means that you will have the ability to reproduce a build later, but how is that going to work if the sources can vary depending on the mood of gnulib developers?
3. While looking at the 'bootstrap' script I have seen an option '--gnulib-srcdir' which is good to have, but it doesn't really solve point 2.
4. An author/maintainer knows best what versions of 3rd. party components he/she is using will work, and if there are no tagged releases of such a component it is wise to include exactly the version it was developed with! (Btw, I am by far not a fan of including every piece of 3rd. party library into sources!)

Short - It would be very neat if you could include exactly the version of gnulib within release tarballs you have developed/tested with.

Cheers,
Chris

**Comment by msva** [comment]
@gvvaughan sorry for some kind of necroposting, but problem with inability to install luaposix in networkless environment using master tarball is still persists (despite of your answer to @morfoh).

Second thing is that your slingshot's "bootstrap" does some black magic, that it is impossible to build the package without it, using "usual" autoreconf+libtoolize+aclocal+autoconf+autoheader+automake, but only possible to build with that bootstrap (which is really pain for distro maintainers).

It is even impossible to somehow say buildsystem "you can take slingshot from here and gnulib from here, but do not try to fetch anything from the internet"

**Comment by gvvaughan** [comment]
Hi Vadim,

Why not start from a release tarball, or checkout from the release branch where bootstrap has already executed and set up all the autoconfigury in advance?

cheers,
Gary

**Comment by msva** [comment]
To be honest, because I'm maintain "9999" (VCS) luaposix package in Gentoo's Lua project. That means, I'm doing an ebuild (something like rockspec, but used for any package in the system), which purpose is to install "master" version. But distro (Gentoo) policy is to keep previously checked out sources (distfiles), including VCS trees, and (in case of vcs) do not checkout new commits if users ask for that (EVCS_OFFLINE=1, if any). That is allowing user to (re)build package from exactly the sources (s)he checked out before (on previous installation, or manually).

The case of offline installation is very useful and allowing users to preliminarily check out all sources, while they have internet connection and build packages later even without internet access (i.e. if user has no internet access at home, but working in the internet from, say, internet cafe, or, maybe, during flight, or half-country train traveling).

**Comment by gvvaughan** [comment]
Understood.

In that case, I recommend running the bootstrap script from your ebuild file, which will call all the autotools in the correct order with the correct arguments among other things rather than reverse engineering the bootstrap process all over again for your ebuild.

Although I'll accept interim patches to the autofoo in luaposix, my medium term plan is to move away from Autotools half-megabyte if shell scripts into a Lua based build system - somewhat like the Luarocks build command, which will cut the size of luaposix distribution by 70% or so. When I finally arrive there, all of the bootstrap issues will go away entirely.

HTH,
Gary

**Comment by msva** [comment]
Actually, I was tried to call "autocrap" things just in my attempt to unbind bootstrap from "internet" dependency ;)
It is no hard to call bootstrap itself (there is even hook for automatic calling bootstraps after pulling repo from distdir to builddir). It is hard to make it don't fetch anything from internet. For now I doing following hook:
```
    if [[ -n ${EVCS_OFFLINE} ]]; then
        die "Unfortunately, upstream uses buildsystem which depends on external submodules, so you won't be able to build package in offline mode. Sorry."
    fi
```
But users complaining anyway :-/

[offtop]
Talking about moving from "autocrap" to anything else — I myself, for my Lua projects do either prepared makefile (with some configurability) or CMake. Although, moving to CMake requires project internals knowledge and diving in the manuals for some time.
[/offtop]

By the way, is it okay to bootstrap in directory where luaposix checkouts, then copy source directory for building for each lua target and each processor architecture inside each lua target?
(I mean, doesn't bootstrap hardcode anything platform dependent in some hidden place?)
And if so, will it be hard to keep "prebuilt" `configure` in the repo, until migration from autotools?

**Comment by gvvaughan** [comment]
> On Sep 19, 2015, at 9:40 PM, Vadim A. Misbakh-Soloviov <notifications@github.com> wrote:
> [offtop]
> Talking about moving from "autocrap" to anything else — I myself, for my Lua projects do either prepared makefile (with some configurability) or CMake. Although, moving to CMake requires project internals knowledge and diving in the manuals for some time.
> 
I have absolutely no plans to jump out of the Autotools frying pan and into the Cmake fire... I actually find Cmake hard to understand, badly documented, and lacking in many of the things that come for free with Autotools (cross-compilation, autotest, shared sources for multi-arch builds, runnable and testable from the build tree without worrying about previous versions installed on the system library path, portable runtime loading, sanity checks and coding standards conformance checking, changelog generation from scm log messages, ability to distribute a package that requires nothing but a make, she'll, and some common UNIX utilities, automated version and release management, and on an on) - I know I can build all that stuff with Cmake, but Autotools provides it already.
</off-topic>

:-)
> By the way, is it okay to bootstrap in directory where luaposix checkouts, then copy source directory for building for each lua target and each processor architecture inside each lua target?
> 
yes, absolutely... that's the way it is supposed to be used. The distributor runs 'bootstrap' and the installer runs './configure; make; sudo make install'.

Actually, if you start from a tagged release on master, and then run bootstrap, you will end up with the exact same set of files that are checked in at the matching tag on the release branch (or equivalently, the contents of one of the release tarballs I make available here on github)- subject to differences in the versions of Autotools you have in comparison to what I used at the time of release, of course.

In fact, I'm still surprised that you want to go to all the effort of redoing this all over again by yourself when I've done it all for you already... especially considering that the HEAD of master may have bugs, incomplete features or experiments that don't work out compared to using a stable release tarball, release tag from the release branch or Luarocks install?
> (I mean, doesn't bootstrap hardcode anything platform dependent in some hidden place?)
> And if so, will it be hard to keep "prebuilt" configure in the repo, until migration from autotools?
> 
no, not hard at all... but still more effort than any of the more stable options I outlined above.

HTH,
Gary

**Comment by msva** [comment]
>  In fact, I'm still surprised that you want to go to all the effort of redoing this all over again by yourself when I've done it all for you already..
So... I'm unsure if I get you right, but if you're talking about doing bootstrap every time package builds, then answer is: some kind of distro specific (although, I'm pretty sure, Arch has same thing). It is nowhere where we can "prepare" sources once and forever.

The "package", as an essence, is just script with some shell variables and some shell functions, which runs at some build/install phase. One of the variables is the source where package manager can get sources. If we talking about release-version, then it's tarball link. But here - it is git repo url.
Then, installation process goes:
1) user says `<package_manager> install =luaposix-9999 #from vcs`.
2) Package manager fetches current repo state to distfiles directory (either `git clone` or `git fetch`, depnds if it already exists) as "bare" git repo (without files tree). Modification of distfiles is prohibited.
3) Package manager clones git repo to temp build dir
4a) enables sandboxing to prevent buildsystem to touch anything outside builddir or destdir (so called "image", empty target dir where package installs it files to)
4b) <doing the things from build receipt>, including copying sources dir multiple times to build for each Lua target user enabled and each ABI architecture (for multilib, like known lib32-lib64-libx32 on x86, or something similar on mips ones).
5) after running "install" phase (with installing files not in the live system, but in the destdir), it merges "image" content in the live system (preventing file collisions).
6) temporary build directory cleans completely # btw, most users has it in the tmpfs

Only way to do not redo all the bootstrap work every time is to either have "configure" script in the sources tree in master's HEAD (depends on upstream) or to have it as patch and put it at preparation stage (actually counts as dirty and bad practice in maintainers manuals).

So single way to "do it right" is to run bootstrap every times user installs the package.

> especially considering that the HEAD of master may have bugs, incomplete features or experiments that don't work out compared to using a stable release tarball, release tag from the release branch
My work is to give the possibility to install package's from VCS's HEAD revision to user (including myself). If user is doing so, then (s)he already manually confirmed (by putting special line in the config) that (s)he understands that it can be broken.
That is he purpose of "live", or, so called, "bleeding edge" packages: no one guarantee it will end build process successfully (since it is not a tarball that can be tested), but OTOH, 
user has possibility to easily test for new feature if, say, (s)he reported bug upstream, upstream fixed it and then said "fixed in HEAD, please test". And user can just install "live" version and test that. Without making the system be like LFS (i.e. don't install anything without package manager) 

> or Luarocks install?
It is bad user practice to install anything systemwide with 3party packagemanagers, uncontrolled by the system one.
And talking about installing non-systemwide — as you can be noticed, Lua 5.2 and 5.3 changed modules path/cpath to prefer system-wide installed modules over locally installed ones: [prooflink](http://www.lua.org/source/5.3/luaconf.h.html#LUA_PATH_DEFAULT).

**Comment by msva** [comment]
btw, actually, I've asked about bootstrap hardcoding because of the issues with:
1) compiling luaposix for lib32 with
```
export CC="x86_64-pc-linux-gnu-gcc -m32" CFLAGS=" -I/usr/include/lua5.1  -fPIC -DPIC" LDFLAGS=" -shared -fPIC"
./configure --prefix=/usr --build=i686-pc-linux-gnu --host=i686-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --libdir=/usr/lib32 --with-ncurses LUA=lua5.1 LUA_INCLUDE=-I/usr/include/lua5.1
```
it says:
```
checking whether we are cross compiling... configure: error: in `/var/tmp/portage/dev-lua/luaposix-9999/work/lua51/luaposix-9999-abi_x86_32.x86':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

2) installing: by default, without any hacks from my side, buildsystem tries to install things to strange places:
a) for PUC-Rio luas: 32bit `posix.so`'s to 64bit INSTALL_CMOD (/usr/lib64/lua/{LUA_ABI})
b) for luajit: posix.so to /usr/lib/lua/5.1 (there is no such path neither in 32bit nor 64bit pkgconfig files).

But both `a` and `b`, as I noticed, is taken from `${LUA_BIN} -e 'print(package.cpath)'` (and both `--libdir` switch for `configure` and `LUA_CPATH` switch for make are ignored) :(

3) I've noticed there is `posix.lua.in` in the `libs/`, but it is never installed with default buildsystem. Is it just as planned? :)

**Comment by gvvaughan** [comment]
1) what does the corresponding chunk of config.log say?
2) the configure is mainly set up for luarocks to call, though I'll take patches for it to work better standalone. Look at how the git rockspec calls configure to see how paths are passed in - either by looking at the code in the file, or running luarocks as described in the README.
3) Yes, exactly as planned - configure substitutes the version number into posix.lua.in to make installable posix.lua.

cheers,
Gary

**Comment by msva** [comment]
1) nevermind, it seems, I found a way to walk around that ;)
2) Ok, i'll try to work on it, although, autotools is a very black magic for me ;) 
3) I meant that `posix.lua` is never installed ;) Just only `posix.so`, `posix/` and `curses.lua` ;)

**Comment by gvvaughan** [comment]
1) okay, great!
2) thanks, much appreciated. I'll try to answer any questions you raise and generally be helpful.
3) it is installed here on my Mac, and by the Travis regression tests that run on Linux automatically for every commit. looks like you've found a bug! If you can fix it, please send a patch, otherwise please try to isolate the cause and file a new issue describing how I can reproduce it... and I will endeavor to fix it.

Cheers,
Gary

**Comment by msva** [comment]
2) it seems, I've found workaround even for that (passing LUA_CPATH to ./configure), but there is some kind of bug (?): it looks like it somewhy uses `dirname` on the value of it, so if I pass `LUA_CPATH=/usr/lib32/lua/5.1` (and same for `lib64` and `lua/5.2` and `lua/5.3`) — it ./configure makes it to be:
```
checking for lua5.1 module directory... ${exec_prefix}/lib64/lua
<...>
checking for lua5.2 module directory... ${exec_prefix}/lib64/lua
<...>
checking for lua5.3 module directory... ${exec_prefix}/lib64/lua
```
Exactly same thing with LUA_PATH (for LMOD).

But, if I add `/` to the end of `LUA_PATH`/`LUA_CPATH` values, then all goes fine. Not that it hard to add slash, but it is a bit kludgy: there is no slashes at the end in the pkg-configure files, so it requires hacks at configure stage.

3) are you sure? ;)
I just noticed
```
all/luaposix-9999/ChangeLog.old:  * Deleted posix.lua loader file not needed anymore in Lua-5.1 module system
```
when grepped for posix.lua over build dir ;)

**Comment by gvvaughan** [comment]
At least insofar as LUA_CPATH is concerned you can override the value that ax_lua.m4 guesses by setting ax_cv_lua_luaexecdir at configure time:

```
$ ./configure ax_cv_lua_luaexecdir=/lookee/here
...
checking for lua module directory... /lookee/here
```

**Comment by msva** [comment]
yeah, `ax_cv_lua_luadir` and `ax_cv_lua_luaexecdir` does the trick.

Btw, a bit of offtop: I also noticed that documentation generation depends on ./configure to be executed before that (and, since ./configure runs separatelly for each lua target and multilib abi, it will be odd to generate all the same documentation for about 8 times in edge case).

So, I doing something like that:
```
    use doc && (
        cp build-aux/config.ld.in build-aux/config.ld
        cp lib/posix.lua.in lib/posix/init.lua
        sed -r \
            -e "s/@PACKAGE_STRING@/${P}/" \
            -i build-aux/config.ld.in lib/posix/init.lua
        mkdir -p doc
        ldoc -c build-aux/config.ld -d doc .
        rm build-aux/config.ld lib/posix/init.lua
    )
```
(where `P` is `PACKAGE_NAME-PACKAGE_VERSION`). Since, as diff says, only difference between `.in`s and "prepared" files is `@PACKAGE_STRING@` replaced with `luaposix 33.3.1`. So, my curent behaviour here assumes, that there will not be any other things for autotools to prepare there ;) Is it okay, or do you planning to add something there someday? :)

**Comment by gvvaughan** [comment]
No promises... but I can't think of anything that I might need to change; so it looks like you have a good solution there already :)
