### ISSUE TITLE
_DEBUG is not declared (which makes luaposix std.strict-incompatible)

### ISSUE THREAD

**Issue by tomonacci** [luaposix/luaposix#186]
This report is against the version distributed through luarocks (I tried installing the latest but for some reason `luarocks install https://raw.github.com/luaposix/luaposix/release/luaposix-git-1.rockspec` failed).

When I `require "posix"` with `std.strict` turned on, I get an error because `_DEBUG` is referenced but not declared in `deprecated.lua`. `_DEBUG` seems to be the only such variable.

```
% lua -lstd.strict -lposix
lua: /usr/share/lua/5.2/posix/deprecated.lua:163: variable '_DEBUG' is not declared
stack traceback:
    [C]: in function 'error'
    /usr/share/lua/5.2/std/strict.lua:44: in function '__index'
    /usr/share/lua/5.2/posix/deprecated.lua:163: in main chunk
    [C]: in function 'require'
    /usr/share/lua/5.2/posix.lua:40: in main chunk
    [C]: in function 'require'
    [C]: in ?
% lua -lstd.strict -e "_DEBUG = false" -lposix
%
```

**Comment by agladysh** [comment]
@gvvaughan What is the status on this? This breaks lua-nucleo's strict mode too.

**Comment by gvvaughan** [comment]
Hi Alexander,

The status is unchanged.   It's very easy to workaround by adjusting the value of `_DEBUG` when requiring each module for which the content of `_DEBUG` is part of the documented interface.  Lua-stdlib has been this way since 2010, and luaposix since 2014.  I don't want to break all the client code that relies on this interface when the workaround is so straight forward.

You could even encapsulate it in your own require function that pushes and pops `_DEBUG` appropriately for the various modules that you want to use with conflicts if you want to hide it.

That doesn't mean I won't consider a clean pull request to make this easier to manage for people who prefer not to (ab)use the global namespace -- as long is it's backwards compatible for code that relies on this long standing convention...

:)

**Comment by agladysh** [comment]
@gvvaughan Fair enough. 

Out of curiosity, do you know of such client code in the wild? (That is maintained by someone else, of course, or it would be too easy :) )

**Comment by gvvaughan** [comment]
@agladysh I do not; but the nature of MIT is that we have absolutely no idea who our clients are :(

**Comment by agladysh** [comment]
@gvvaughan well, you broke everything (at least for us) post v.30. I doubt that the proposed _DEBUG change is more drastic...

**Comment by gvvaughan** [comment]
@agladysh Sorry about that.  I think this occasional unexpected (from the user's perspective) breakage was part of the reason @rrthomas and I moved to semantic versioning soon afterwards, so that breaking changes would at least be called out by a change to the major version number.

I'm not unconvinced of your argument by the way, I'm just not motivated enough to work on the changes.  Please make a pull request, and even if it is backwards incompatible, I'll just save it up for v42.0.0.

**Comment by gvvaughan** [comment]
And with luaposix 34.0.2, the conversion to non-polluting shared `std._debug` is complete.

Thanks for impressing the importance of this issue on me, and sorry it took so long for me to get around to fixing it.
