### ISSUE TITLE
posix.dirent.files does not return reason for failure

### ISSUE THREAD

**Issue by istr** [luaposix/luaposix#207]
The iterator ```posix.dirent.files()``` throws with ```attempt to call a nil value``` if called on a non-existent directory. I would expect it to behave like ```io.lines``` on a non-existing file, printing the reason for the failure.

```lua
local dirent = require'posix.dirent'

print(dirent)

for broken in dirent.files('/notexistent') do
  print(broken)
end
```

result:
```sh
lua dirent.lua 
table: 0x41c1d448
lua: dirent.lua:5: attempt to call a nil value
stack traceback:
	dirent.lua:5: in main chunk
	[C]: at 0x00405140
```

expected:
```sh
lua dirent.lua 
table: 0x41c1d448
lua: dirent.lua:5: bad argument #1 to 'files' (/notexistent: No such file or directory)
stack traceback:
	dirent.lua:5: in main chunk
	[C]: at 0x00405140
```

**Comment by gvvaughan** [comment]
Thanks for the report.

As the luaposix bindings continue to get "thinner", the C implementations of `dirent.file` and `dirent.dir` will be superseded by Lua implementations over bindings to `opendir`, `readdir`, `seekdir` and `closedir`.

You'll notice from the `examples/dir.lua` contents that the current semantics require first checking for a `nil, "error message"` return from `dirent.files` and propagating an error before passing the iterator into a loop.  It's arguable whether this is more flexible than having `dirent.files` instead throwing the error itself so it can be called directly from the `for` loop, but then requiring user facing code to use `pcall` to diagnose the error without a stack-trace.

That aside, the behaviors of our current and future APIs should be consistent with how the Lua core behaves... and it seems to be a simple matter of throwing an error from the iterator rather than returning a `nil, "error message"`, so I'll fix it presently.
