### ISSUE TITLE
Prevent bugs, remove ability for `execx`'s `task` argument to be a string

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#216]
Given that `spawn` was renamed from `system` only a few months ago, I don't think this is a big problem. I have two reasons for wanting this:

1. By using Lua for shell scripting I'm trying to help cure shell quoting, not prolong it. I have (in my brain) a better API for running shell commands in a more natural syntax, but that will make a new module (to compete with Python's `sh`). For luaposix, better just provide a list of command and arguments.

2. By removing the ability to pass a string command, the type constraint on the rest of the arguments to `execx` can be lifted, which allows arbitrary arguments to be passed to function tasks. Without this, only functions taking exclusively strings can be used, and yes, I've already hit this problem in cw.

See luaposix/luaposix#215.

**Comment by gvvaughan** [comment]
1. I have, on my computer, a half-baked new FileUtils module that does exactly this to make writing file shuffling rules within Luke easier to write - i.e. more like a make rule than a lua function.  I'd be happy to send you a copy so you can see the architecture and we can collaborate rather than work on competing implementations!

2. I should have read this before my rebuttal of your removal of the `system` alias.

**Comment by rrthomas** [comment]
Let me get to the prototype stage with "shell scripting in Lua", which is what I'm trying to do, and then let's look at each other's code. Given my Lenten fast, that'll be after Easter (I'm desperately trying to finish up all my pre-Lent obligations now!).

**Comment by gvvaughan** [comment]
cherry picked the matching changeset from #215.
