### ISSUE TITLE
rockspec vs bootstrap out of sync?

### ISSUE THREAD

**Issue by karlp** [luaposix/luaposix#233]
The README.md file says, ```Dependencies are listed in the dependencies entry of the file rockspec.conf. ``` but that doesn't list ldoc or specl, both of which turn out to be requirements when you run bootstrap.

```
karlp@cuth:~/src/luaposix (master)$ ./bootstrap 
bootstrap:   error: Prerequisite LuaRock 'ldoc 1.4.2' not found. Please install it.
bootstrap:   error: Prerequisite LuaRock 'specl 14.1.0' not found. Please install it.
bootstrap:   error: Missing rocks:
<<< more snipped
```

**Comment by gvvaughan** [comment]
Thanks for the report.  In a way you are right, because the README.md isn't really there to help luaposix developers bootstrap a release, but doesn't make that very clear.

Bootstrapping is a process you need to complete *before* configuring and building.  The README.md is written as if you have just downloaded an already bootstrapped release from the release branch or from github, both of which are already bootstrapped.

If you do want to bootstrap the whole thing yourself, then you will need Perl, Automake, Autoconf, GNU M4, and an installed and working ldoc and specl among others *in addition* to the tools you need to configure and build (bourne shell, make etc).  In order to get a working specl and ldoc, you will also need several other lua modules installed correctly.

Much easier than building all of this for yourself from scratch when you are not yet familiar with all of the tools involved is to preferably:

  luarocks install luaposix

Otherwise, start from a release tarball which uses the familiar:

  ./configure
  make
  sudo make install

I plan to rewrite all the README files for the projects I maintain in the near future to make it clearer that we only plan to support the first, easiest method... and otherwise assume that you already know how to bootstrap and configure if you wish to build an unreleased luaposix for yourself or your customers.

HTH,
Gary

**Comment by karlp** [comment]
If only luarocks was easy/sane to use with multiple different lua versions :)  I did end up going that way, but it was rather unpleasant as well :)  I'm quite used to bootstrap/autogen/cruft when building from a source checkout rather than a tarball, but I had still expected the requirements to match up.  At least, thankfully, your bootstrap actually checks for the requirements it really does need, so it was clear what was needed, this was just a minor ticket to let you know that it could be more selfconsistent.  (You could also just drop the sentence saying to look at the rockspec, it will be used by rocks anyway, so no need to refer to it at all as a human?)
