### ISSUE TITLE
 C compiler cannot create executables

### ISSUE THREAD

**Issue by studentz** [luaposix/luaposix#238]
System 
lsb_release -a  Description:	Ubuntu 14.04.3 LTS
lua -v Lua 5.2.3  (interpreter from system)
luarocks  LuaRocks 2.2.0beta1

Torch
Lua version: 5.1 (iterpreter from lua)
Configuration files:
System: /home/me/torch/install/etc/luarocks/config.lua (ok)

ERROR

/configure LUA='/home/me/torch/install/bin/luajit' LUA_INCLUDE='-I/home/me/torch/install/include' --prefix='/home/me/torch/install/lib/luarocks/rocks/luaposix/33.3.1-1' --libdir='/home/me/torch/install/lib/luarocks/rocks/luaposix/33.3.1-1/lib' --datadir='/home/me/torch/install/lib/luarocks/rocks/luaposix/33.3.1-1/lua' --datarootdir='/home/me/torch/install/lib/luarocks/rocks/luaposix/33.3.1-1' && make clean all
## --------------------------- ##

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/luarocks_luaposix-33.3.1-1-6456/luaposix-release-v33.3.1':
configure: error: C compiler cannot create executables
See `config.log' for more details

Error: Build error: Failed building.

NOTE
I can compile any program using gcc or g++

**Comment by jjandresson** [comment]
You should search the `config.log` file for "compiler works" to see exactly what the error message from `gcc` is - most likely some flags it doesn't understand.

-jj

**Comment by gvvaughan** [comment]
What JJ said - almost certainly bad flags confusing your compiler. The error message tells you where to look to find out exactly where.

**Comment by studentz** [comment]
Thanks JJ and gvvaughan.
The problem was with Lua 5.2, I compiled using Lua 5.1 without problem. I will check the log file.
BTW the config file is the /tmp/.. or inside torch directory?

**Comment by gvvaughan** [comment]
there will be a config.log in the same directory you were in when you ran configure...

**Comment by FrancisHe** [comment]
I have the same problem, this is the output:

> configure:3218: gcc -qversion >&5
gcc: ./specs: Is a directory
configure:3229: $? = 1
configure:3249: checking whether the C compiler works
configure:3271: gcc    conftest.c  >&5
gcc: ./specs: Is a directory

the problem is gcc will use ./specs because of wrong setting, such as LIBRARY_PATH or LPATH or GCC_EXEC_PREFIX.
['specs' directory interferes with the operation of gcc in configure scripts.](https://gcc.gnu.org/ml/gcc-help/2010-05/msg00293.html)

I have the same problem, because somebody made a wrong setting in my system:
echo $LIBRARY_PATH   
:/usr/local/lib

That make LIBRARY_PATH empty solved my problem.

**Comment by xinleipan** [comment]
I used lua 5.1.5 and set my $LIBRARY_PATH empty , but it does not help ...
