### ISSUE TITLE
Luaposix won't compile with luarocks.

### ISSUE THREAD

**Issue by BrokModding** [luaposix/luaposix#251]
Hello. I was trying to build luaposix with luarocks. I did it like this:

`luarocks install luaposix`

but when process is near to complete, in console I can see following text:

```
Installing https://luarocks.org/luaposix-33.4.0-1.src.rock
./configure LUA='lua5.1.exe' LUA_INCLUDE='-Ic:/lua/include' --prefix='c:\lua\sys
tree/lib/luarocks/rocks/luaposix/33.4.0-1' --libdir='c:\lua\systree/lib/luarocks
/rocks/luaposix/33.4.0-1/lib' --datadir='c:\lua\systree/lib/luarocks/rocks/luapo
six/33.4.0-1/lua' --datarootdir='c:\lua\systree/lib/luarocks/rocks/luaposix/33.4
.0-1' && make clean all

(here is text about command '.' cannot be found)

Error: Build error: Failed building.
```

What should I do now?

**Comment by gvvaughan** [comment]
Hi,

Thanks for the report. I'm actually amazed it even got that far... testimony to the power of autoconf! ;-)

I don't have any way of testing on Windows. I was pretty sure that Windows doesn't have a POSIX runtime, so it's likely that even if you manage to get it to install, much of the good stuff will have no access points to call out to anyway.

If you discover that I'm wrong and that modern Windows has implemented enough of POSIX to be able to employ libposix usefully, I'd be happy to apply any patches you make to get it working.

Alternatively, if there's a straight forward way to run regression tests for Windows from github along the lines of Travis for Linux, I'd consider setting that up.

I haven't used Windows since Win98, but you might get a better response from the lua or luarocks mailing lists?

Cheers,
Gary
