### ISSUE TITLE
mkdtemp is available in a system, but luaposix did not detect it

### ISSUE THREAD

**Issue by hishamhm** [luaposix/luaposix#269]
This produced an error when running LuaRocks in a user's system:

https://github.com/luarocks/luarocks/issues/696#issuecomment-296503289

Looks like mkdtemp() is available in the system, but luaposix failed to bind it. @spc476 may be able to give more information about the system in question.

**Comment by spc476** [comment]
It's an older system:

% uname -a
Linux lucy.roswell.conman.org 2.6.9-100.EL.plus.c4smp #1 SMP Fri Feb 18 03:46:19 EST 2011 i686 i686 i386 GNU/Linux

**Comment by gvvaughan** [comment]
Sorry for the delay.

The problem is that in order to avoid #ifdef hell, luaposix tries to bind POSIX.2008 APIs in the first instance, and falls back to POSIX.2001 if the system headers don't declare their support of POSIX.2008.  If your system is POSIX.2008 compliant despite system header defines, you  can set `CPPFLAGS=-DLPOSIX_2008_COMPLIANT' at compile time to force binding of `mkdtemp` among others.

If your system is somewhere between 2001 and 2008 compliance, I recommend a C library upgrade if you want 2008 features from a released luaposix.

Beyond that, you can always download the sources and patch the body of `Pmkdtemp` in `ext/posix/stdlib.c` not to hide behind `LPOSIX_2008_COMPLIANT` guards.

Especially now that I've finally excised the last of Autotools from the source tree, I'm reluctant to go back to painstaking probing of every API in the host system luaposix wants to bind.  The long-term solution is to push that work down to the nascent `libposix` shim project in `gnulib`, and always link against that, in the knowledge that it will patch over buggy libc implementations and fill in missing calls.

  https://www.gnu.org/software/gnulib/manual/html_node/POSIX-Substitutes-Library.html

Sadly, my employer won't sign FSF paperwork required to continue contributing to GNU projects.  Maybe it's not that important these days now that nearly all the diversity in POSIX operating systems has given way to Linux and macOS?

If you have any ideas on a better way forward that would enable luaposix to always export a full API in the face of substandard host support, that would be awesome.

I know that doesn't improve this issue specifically, but hopefully one of the workarounds above will.

Cheers,
Gary
