### ISSUE TITLE
Adds random trailing zeros when connecting to abstract random space

### ISSUE THREAD

**Issue by tkim5574** [luaposix/luaposix#284]
When I try to connect to abstract namespace (ex: \0mytarget), it adds random trailing zeros at the end of the path which makes it impossible for the socket to connect to the correct path. When I try binding, it binds to mytarget\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0 not mytarget.

**Comment by gvvaughan** [comment]
Thanks for the report.

I don't actually use this feature myself (Mac OS X doesn't support it), so I wonder if you could write a failing test for me, please?  (either as a specl example if that's straight forward, or else as a small lua program that will work only when the bug is fixed)

**Comment by tkim5574** [comment]
`local socket = require('posix.sys.socket')`
`local connect_to = '\0mytemp'`
`s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)`
`local con = socket.connect(s, {family = socket.AF_UNIX, addr = connect_to})`

You are going to have to open up socket with an abstract namespace. Could be done in python easily. Below is the sample python code:

`from socket import*`
`sock = socket(AF_UNIX, SOCK_STREAM)`
`sock.bind('\0mytemp')`
`sock.listen(1)`
`conn = sock.accept()[0]`

It is weird. I've been testing it on different machines and it works 8 out 10 times on my Debian but fails every time on my Gentoo machine. If you strace the pid of the lua file, you will see that 
it adds random trailing zeros:

@'mytemp\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0'

Was looking at the code, it might have something to do with how you define length and do memcpy?

**Comment by gvvaughan** [comment]
Okay, I've managed to reproduce this in a VM.  I'm pretty sure the trailing NUL bytes are always there, because I get a connection refused error on Ubuntu even though strace shows the socket name as `@'abstractns'` due to the trailing NUL mismatch versus your python server.

Reading the Linux connect(2) man page, it seems as though returning `sizeof(*sau)` for AF_UNIX sockets is what makes all the trailing zeros part of the name.  I've just pushed a fix that passes back the path length adjusted `struct sockaddr_un` size, which allows me to connect.

Thanks again for the report!  Please let me know if you notice anything else misbehaving.
