### ISSUE TITLE
Problem with instalation of  luaposix on Windows7

### ISSUE THREAD

**Issue by ldurniat** [luaposix/luaposix#297]
Hi,

I tried install luaposix using command

`luarocks install luaposix`

I got two errors:

1. https://i.imgur.com/OayVwt6.png
I solved it by using file named uname.bat:

    @echo off
    echo ^Windows

2. https://i.imgur.com/Ygo64qH.png
I got error message: `luke: fatal cannot find LDocs generator` I have installed LDoc using luarocks.

Can you help me?

**Comment by gvvaughan** [comment]
Thanks for the report.

Please note, from the included README.md:

    This is a POSIX binding for LuaJIT, Lua 5.1, 5.2 and 5.3; like most libraries it simply binds to C APIs on the underlying system, so it won't work on non-POSIX systems

Last I looked on Windows (more than a decade ago), one of the MSVC variants did provide a half-baked POSIX environment with many things entirely unimplemented and the rest spuriously renamed with leading underscores. You might be able to build it with cygwin, or mingw and perhaps the new Ubuntu subsystem I’ve read about - although some of the key features of POSIX like cheap forks will most likely be extremely slow. I’m afraid I don’t have (or want) windows access so I can’t help very much, but if you get it working without major surgery or gross hacks I’ll be happy to merge pull-requests.

The release version is not supposed to require LDoc, because all the html is included. So that’s a real big I’ll fix if I can reproduce on Linux or macOS.

**Comment by gvvaughan** [comment]
I cannot reproduce the fatal LDoc error on Unix, so not a real bug after all.  Installing luaposix on Linux and macOS with or without an `ldoc` available works correctly. My best guess is that searching `PATH` for binaries on Windows doesn't behave normally, and after failing to find an `ldoc` binary, build-aux/luke tries to find the Unix `true` command which also doesn't exist on Windows then gives up and bails out altogether at that point.

You might get a further if you can figure out how to set Windows equivalent to $PATH in the luke execution environment to contain the directory with the installed `ldoc` command - is `eval $(luarocks -path)` a thing in Windows?

**Comment by ldurniat** [comment]
For now I don't time to figure out why this is not working. 

Have a nice day.

Thanks for your help:)

**Comment by jeffktripplite** [comment]
@ldurniat Ever figure out this issue? I'm having the same ldocs error.

**Comment by curicm** [comment]
Same on win11, no WSL, trying it locally.

**Comment by nagolove** [comment]
The same error on msys2-mingw64. I installed ldoc manually via LuaRocks and moved ldoc.bat to same bash ldoc file. Now I can run ldoc from msys2. But I could not figure out to compile luaposix because of ldoc is essential component. I use win10.

**Comment by gvvaughan** [comment]
I'm happy to apply a clean patch if someone can figure out how to build on Windows.

But I'm pretty surprised that people want to build luaposix for a non-POSIX compliant OS... The functions it wraps don't even exist unless you use WSL, at which point everything should work the same is it does on Linux proper.

**Comment by nagolove** [comment]
@gvvaughan I think ldoc should be additional dependency for build luaposix that no break build process if it is not found.
Your are right about non-POSIX OS but I am trying to move my lua project from linux to windows and has for example `readline` rock which reference for `luaposix`. May be I will rewrite console input for more platform-independent way.
