### ISSUE TITLE
posix.sys.stat.umask requires an argument

### ISSUE THREAD

**Issue by hishamhm** [luaposix/luaposix#305]
I'm trying to get the current umask value in numeric form. Documentation states that the argument for `posix.stat.umask` is optional.

https://luaposix.github.io/luaposix/modules/posix.sys.stat.html#umask

However the argument is required:

```
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> posix = require"posix"
> print(posix.version)
posix for Lua 5.3 / luaposix 34.0.4
> stat = require"posix.sys.stat"
> print(stat.umask())
stdin:1: bad argument #1 to 'umask' (int expected, got no value)
stack traceback:
	[C]: in function 'posix.sys.stat.umask'
	stdin:1: in main chunk
	[C]: in ?
> 
```

`posix.umask` accepts being called with no arguments, but that returns in string `rwx` format.

**Comment by gvvaughan** [comment]
Hi Hisham,

The docs for the thin posix.sys.stat.umask binding are wrong (I'll fix them for the upcoming release), because neither does umask(2) support an optional cmask argument:

http://pubs.opengroup.org/onlinepubs/9699919799/functions/umask.html

But it's quite easy to use this call to get a numeric current umask by doing what you would do in C:

```lua
local umask = require 'posix.sys.stat'.umask
local cmask = umask(0)
umask(cmask)
```

This is actually what the implementation of posix.umask is doing if you ignore the mode strong conversions.

Thanks for the report!
