### ISSUE TITLE
Why have static functions in _helpers.c?

### ISSUE THREAD

**Issue by ComputerNerd** [luaposix/luaposix#318]
Is there a particular problem you were trying to solve by doing this? I am willing to submit a pull request to split _helpers.c into _helpers.h and _helpers.c if this is not the case. The advantage of this is that compiler won't generate duplicate machine code.

**Comment by gvvaughan** [comment]
AFAICT those static declarations predate my being maintainer, although I did propagate them into `_helpers.c` when I broke up the `posix.c` monolith. A wild guess is that the monolith declared unexported functions as static until then.

Now that luaposix is built as multiple independent modules, where the source of each module includes all of `_helpers.c`, the m/c duplication between the modules is unavoidable. However, if you are using `posix.c` to roll a unified single luaposix library, I think injecting a new first line of code to `#include "_helpers.c"` will prevent code duplication more easily? I'll definitely merge a PR with that change.

**Comment by ComputerNerd** [comment]
First of all thank you for breaking up posix.c I did not realize that at one point everything was one file. I like how luaposix is separated out into groups.

Is posix.c still used by anyone? It was not used while building it with luarocks make.

I should have looked more closely into how luaposix is built. Like you mentioned I see that each module is a shared library. What would think about each shared library having a dependency on a helpers shared library?

**Comment by gvvaughan** [comment]
Hi, Thanks for the props :-)

The single `posix.c` is not used by default, but there are people with tiny host systems that customize and build manually with it - and actually, it will already correctly include `_helpers.c` exactly once.

I’m not keen on the idea of raising the build complexity by making a separate `helpers.so` because it buys so little in exchange. If you prefer a single copy of the code in `_helpers.c` in memory, you can compile `posix.c` to `posix.so` from the command line and drop it into LUA_CPATH - Lua code doesn’t even need to change and will still find e.g. `local unistd = require “posix.unistd”` just as it would if all the sub modules were compiled and installed individually :-)

**Comment by ComputerNerd** [comment]
OK that is fine. I will close this issue. I am using LTO which should handle this issue anyway. You are right that each *.so file is already pretty small.
