### ISSUE TITLE
pwd.getpwuid fails with 0.0 as input

### ISSUE THREAD

**Issue by emberfade** [luaposix/luaposix#349]
I'm fairly new to Lua. If I made any mistakes please let me know.

The following behaviour seems to depend on the lua version. It has been tested on Arch Linux.

Lua 5.1 runs successfully whereas 5.4 causes an error.

### Current behaviour for 5.4

```lua
local pwd = require('posix.pwd')
local a = pwd.getpwuid(1000.0)
local t = pwd.getpwuid(0.0)
```
will cause an error with 0.0 but not with 1000.0
```
lua: a.lua:3: bad argument #1 to 'getpwuid' (int expected, got number)
stack traceback:
	[C]: in function 'posix.pwd.getpwuid'
	a.lua:3: in main chunk
	[C]: in ?
```

From what I can tell this will probably only happen with 0.0.

### What I think happens

The function `Pgetpwuid` calls `checkint` https://github.com/luaposix/luaposix/blob/5b68a50b39a1de5a91b2ec3a634cf60d86d535e6/ext/posix/pwd.c#L139-L151
which itself calls `checkinteger` https://github.com/luaposix/luaposix/blob/5b68a50b39a1de5a91b2ec3a634cf60d86d535e6/ext/include/_helpers.c#L163-L167
and then `lua_tointeger`
https://github.com/luaposix/luaposix/blob/5b68a50b39a1de5a91b2ec3a634cf60d86d535e6/ext/include/_helpers.c#L154-L161

After `lua_tointeger` we have `d = 0` and the provided number is still a float. Therefore `argtypeerror` is called causing the error.

### Possible solution

I tested the following change on a patched lua-posix Arch Linux package, which seems to work with Lua 5.4.  Though I don't know if there are any unintended consequences due to the change.

```diff
diff --git a/ext/include/_helpers.c b/ext/include/_helpers.c
index 6b13a88..a7282e0 100644
--- a/ext/include/_helpers.c
+++ b/ext/include/_helpers.c
@@ -154,8 +154,9 @@ checktype(lua_State *L, int narg, int t, const char *expected)
 static lua_Integer
 checkinteger(lua_State *L, int narg, const char *expected)
 {
-	lua_Integer d = lua_tointeger(L, narg);
-	if (d == 0 && !lua_isinteger(L, narg))
+	int isnum = 0;
+	lua_Integer d = lua_tointegerx(L, narg, &isnum);
+	if (!isnum)
 		argtypeerror(L, narg, expected);
 	return d;
 }
```

**Comment by gvvaughan** [comment]
Thanks for the feedback.

Lua 5.1 stored all numbers (integers or floats) as 53 bit IEEE 754 doubles.  More recent Lua releases including 5.4, but I forget when exactly, added real low level integer types.  luaposix tries to work correctly with Lua 5.1 and newer, including luajit, within the constraints of the various apis exposed by each, but misses some corner cases in doing that.

Your suggestion uses a call that is not supported by Lua 5.1 and would prevent luaposix compiling there.

I thing passing a floating point number to `getpwuid` is not really sensible (even though older Lua interpreters will store it as a float internally) because UNIX uids are always integers -- there is no uid 1001.25!  Better to change your code to `pwd.getpwuid(0)` IMHO.

Nonetheless, if you find a way to reliably force integer equivalent floats to real integers that works on luajit and Lua 5.1+ that is not too torturous, please do submit a PR.

**Comment by emberfade** [comment]
Thank you for your thorough answer.

> Your suggestion uses a call that is not supported by Lua 5.1 and would prevent luaposix compiling there.

Are your referring to `lua_tointegerx`? I compiled luaposix with the suggestion for 5.1 and it works with Lua 5.1 and LuaJIT. What I did see is that 5.1 and 5.2 would accept 1000.25, the others didn't. But that seems to be the same behaviour as now, if I tested this correctly.

The code in
https://github.com/luaposix/luaposix/blob/5b68a50b39a1de5a91b2ec3a634cf60d86d535e6/ext/include/compat-5.2.c#L514-L520
gives `lua_tointegerx` which I think is included, if `LUA_VERSION_NUM == 501`. Would that be sufficient for 5.1?

> I thing passing a floating point number to `getpwuid` is not really sensible (even though older Lua interpreters will store it as a float internally) because UNIX uids are always integers -- there is no uid 1001.25! Better to change your code to `pwd.getpwuid(0)` IMHO.

I do agree. It shouldn't be problem to use `math.tointeger()`. It was just really unfortunate that the behaviour changed and only for that one case.

> Nonetheless, if you find a way to reliably force integer equivalent floats to real integers that works on luajit and Lua 5.1+ that is not too torturous,

Could you perhaps test my suggestion and see if it works for you as well? Hopefully, I didn't make a mistake compiling for 5.1

**Comment by gvvaughan** [comment]
I totally spaced on the compat code, and you are quite right! Let me see if I can merge this later today. Thanks for persevering with me 😁
