### ISSUE TITLE
Lazy loading of posix.sys.stat fails in both 35.1 and 36.1

### ISSUE THREAD

**Issue by parke** [luaposix/luaposix#355]
Using Luaposix 35.1, `posix.sys.stat` fails to load lazily:

```
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> posix = require 'posix'
> print ( posix )
table: 0x5609e3374c00
> print ( posix .sys )
table: 0x5609e3359650
> print ( posix .sys .stat )
nil
```

Using Luaposix 36.1, _**even `posix.sys`**_ fails to load lazily:

```
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> posix = require 'posix'
> print ( posix )
table: 0x55df84217a50
> print ( posix .sys )
nil
```

For someone familiar with the Luaposix source code (i.e., more familiar than I am), it might be possible (trivial even?) to write unit tests to test the lazy loading of all sub-modules.

**Comment by gvvaughan** [comment]
Thanks for the report 👍

Fixed in master now, but see NEWS.md for my rationale for deprecating this pattern.

**Comment by parke** [comment]
Thanks for the fix!

Below are two additional comments.

**First**, I realized there is (or was, if you have now fixed it) another problem with how sub-modules load. 

Namely:  Even if you explicitly load `posix.sys.stat`, it is still not available via the main `posix` module.

 Here is a demonstration with 36.1.

```
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> posix = require 'posix'
> require 'posix.sys.stat'
table: 0x55849e587480
> print ( posix )
table: 0x55849e58db60
> print ( posix .sys )
nil
```

**Second**, regarding your rationale:

> `posix.sys.*` submodules are correctly preloaded into the module table returned by `require 'posix'` so that this undocumented, deprecated and slow way to access the functions therein continues to work for now:
> 
>     local posix = require 'posix'`
>     local stat  = posix.sys.stat.stat`

* "are correctly preloaded" - There is a difference between "preloading" and "lazy loading".  Lazy loading would (probably) be implemented via an `__index()` metamethod, and loading would only happen upon lookup.

* "undocumented" - Previously, it was [documented](https://web.archive.org/web/20200130040147/http://luaposix.github.io/luaposix/modules/posix.html#__index).  If, in the future, you remove this functionality, you run the risk of (unnecessarily?) breaking legacy code.

* "slow" - Pre-loading will be slower than lazy-loading.  Specifically: Lua programs that do not use the functions will still pay the overhead cost of loading them.

* "slow" - I'd be willing to bet that 4 Lua table lookups are faster than: the overhead of the system call plus the creation of the Lua table that stores the result.  For example, the creation of the [`PosixStat`](http://luaposix.github.io/luaposix/modules/posix.sys.stat.html#PosixStat) result table itself involves looking up 13 strings.  (Indeed, it would not surprise me if the 4 Lua table lookups are faster than just the C-language `stat()` system call by itself.)

* "continues to work for now" - I suspect that lazy loading of `posix.sys.*` never worked.  Are you aware of a version of Luaposix in which it did work?  (I am not, but I only checked 35.1 and 36.1.)

* `local stat = posix.sys.stat.stat` - There are a finite number (around 200?) of locals available in each block.  Also, putting every function in a local (or even in its own global) fills up (pollutes?) the namespace.  Imo, storing `stat()` in a `local` would be premature optimization.  But, of course, as such optimization is entirely optional, I cannot really object.

* `local stat  = require 'posix.sys.stat'.stat` - Are you suggesting a top-level local, or separate locals inside each function that calls `stat()`?

* I try to accomplish any given programming task by writing as few lines of code as possible.  (As long as the result has good readability and reasonable efficiency.)  Therefore, I'd greatly prefer being able to access all of Luaposix via a single `posix = require 'posix'`.  Fewer lines of code written means fewer lines of code to maintain.

**Comment by gvvaughan** [comment]
Aloha.  Thanks for the thoughtful feedback :-D

>  Even if you explicitly load posix.sys.stat, it is still not available via the main posix module.

It was never designed to work that way, and I'm not aware of any Lua modules that work like that.  It's up to the caller to assign the returned table into whatever structure you prefer prior to calling the APIs.

    local posix = { sys = { stat = require 'posix.sys.stat' } }

> Lazy loading would (probably) be implemented via an __index() metamethod, and loading would only happen upon lookup

Yes indeed. However, since the top-level already has to load all the submodules into memory to copy each of the functions they contain into the top-level 'posix' table, there's no need to "lazy load" anything... it's already loaded, so I just populate the subtables as an affordance for anyone that likes the hierarchical namespace over calling everything from the top level.  Note: there are some differences, because the top-level functions often have Lua wrappers to conform to the original top-level only API for code that was written for that.

> Previously, it was [documented](https://web.archive.org/web/20200130040147/http://luaposix.github.io/luaposix/modules/posix.html#__index). If, in the future, you remove this functionality, you run the risk of (unnecessarily?) breaking legacy code.

I have no plans to break backwards compatibility, but I'm not documenting it anymore due to the much lighter method of loading only the submodules you need being available.  For example, if you have a project that only uses, say, sockets from luaposix... you could bundle just the socket module sources, or at least avoid loading the other 28 unused modules.

> I suspect that lazy loading of posix.sys.* never worked. Are you aware of a version of Luaposix in which it did work?

When I split luaposix up into submodules, I mis-implemented the mis-named lazy loading of the 'sys' sub-hierarchy :-(
> Pre-loading will be slower than lazy-loading. Specifically: Lua programs that do not use the functions will still pay the overhead cost of loading them.

Agreed.  But I don't plan to include an additional lazy-loading-only API in luaposix, so we're stuck with preloading to populate the legacy top-level posix table.  A good option for your use case would be to set up a lazy-loading wrapper to pull in only the modules you reference from your code using `__index` metamethods.  Beware of the differences between module APIs and same-name wrapper functions in the top-level 'posix' table though -- in case you have code that relies on the wrappers at the moment.

> For example, the creation of the [PosixStat](http://luaposix.github.io/luaposix/modules/posix.sys.stat.html#PosixStat) result table itself involves looking up 13 strings. (Indeed, it would not surprise me if the 4 Lua table lookups are faster than just the C-language stat() system call by itself.)

I haven't measured, but seems reasonable to me.  I'm keen to continue supporting old code with the slow undocumented APIs nonetheless.

>  Also, putting every function in a local (or even in its own global) fills up (pollutes?) the namespace. Imo, storing stat() in a local would be premature optimization. [[...]]  Are you suggesting a top-level local, or separate locals inside each function that calls stat()?

For a very long time all the code I maintain tries to import exactly the symbols it needs into the module namespace.  That way you pay the price of loading C-modules to populate the module level locals just once when loading the calling module.   But I have no objection to any other style you prefer :-)

I find the noise of multiple-'.' separators in all those calls distracting, where module level locals cache everything and let me concentrate on the program logic with short succinct symbols quietly going about their work.

>  I'd greatly prefer being able to access all of Luaposix via a single posix = require 'posix'.

I won't break your code on purpose.   But I also won't document it, because of how inefficient it is... my M1 Mac pauses for 4 or 5 seconds for `local posix = require 'posix'` as it loads 29 C-modules and weaves them into the legacy wrappers and preloaded subtables.  `local stat = require 'posix.sys.stat'.stat` has an unnoticable delay.  I'd be interested to learn whether setting up your own `__index` based lazy-loading tables without all the legacy Lua wrapper functions works well though?

**Comment by parke** [comment]
> Yes indeed. However, since the top-level already has to load all the submodules into memory to copy each of the functions they contain into the top-level 'posix' table, there's no need to "lazy load" anything... it's already loaded, so I just populate the subtables as an affordance for anyone that likes the hierarchical namespace over calling everything from the top level.

Well, you could lazy-load everything, including the constants.

> Note: there are some differences, because the top-level functions often have Lua wrappers to conform to the original top-level only API for code that was written for that.

Wow, that is quite surprising!  And potentially confusing.  I didn't know that some top level functions are different from the same-named functions in the sub-modules.  Are these API differences documented anywhere?

At present, I am not using any top level functions.  I only use the sub-modules.  (I just thought the sub-modules would lazy load, as I believe happens with some modules in Python.)

> A good option for your use case would be to set up a lazy-loading wrapper to pull in only the modules you reference from your code using __index metamethods. Beware of the differences between module APIs and same-name wrapper functions in the top-level 'posix' table though -- in case you have code that relies on the wrappers at the moment.

At present I am primarily using Luaposix in my Lush module.  Lush contains functions that are useful for writing shell-script style programs in Lua (instead of Bash, for example).

Now that I know that lazy loading is not supposed to work for `require 'posix' ; posix .sys .stat .stat()`, I'll just preload `'posix.sys.stat'` and assign it to `posix.sys.stat` myself.  I don't mind the "overhead" of preloading.  (More on that below.)

I only reported the issue with lazy loading because I read about it in the documentation and figured if it was documented, then it should work as documented.

> I find the noise of multiple-'.' separators in all those calls distracting, where module level locals cache everything and let me concentrate on the program logic with short succinct symbols quietly going about their work.  (I'm guessing they are not?)

As do I.  I've written a `namespace` module.  All my modules use it.  Namespaces allow each module to have its own global, public, and private namespaces.  When I import/require module A into module B, all of module's A's global symbols are exposed inside module B's internal namespace (provided each global symbol from A is unused in B's internal namespace at the time of import).  So basically, each of my modules gets to choose which of its symbols to "inject" into the internal namespace of any module that imports/requires it.  I got tired of "globalizing" commonly used imported symbols in each separate program that required a module, so I decided to automate the process.

> I won't break your code on purpose. But I also won't document it, because of how inefficient it is... my M1 Mac pauses for 4 or 5 seconds for `local posix = require 'posix'` as it loads 29 C-modules and weaves them into the legacy wrappers and preloaded subtables. `local stat = require 'posix.sys.stat'.stat` has an unnoticable delay. I'd be interested to learn whether setting up your own `__index` based lazy-loading tables without all the legacy Lua wrapper functions works well though?

Have you profiled this slowdown?  Because your M1 Mac is 30+ times slower than my first generation single core Raspberry Pi model B with 256MB of RAM.

```
$ time ./lua -e "local posix = require 'posix' ; print (posix)"
table: 0x119ff0

real    0m0.130s
user    0m0.070s
sys     0m0.057s
```

Furthermore, your M1 Mac is 800 times slower than my fairly modern but definitely mid-range Ryzen 5600G CPU.

```
$ time ./lua -e "local posix = require 'posix' ; print (posix)"
table: 0x556eec5d2f00

real    0m0.005s
user    0m0.005s
sys     0m0.000s

```

Fyi, I build and install both Lua and Luaposix using an installation script that I wrote.  I don't use third-party installers.  So I know exactly what my `package.path` and `package.cpath` are.

**Comment by gvvaughan** [comment]
Ugh, I could have sworn I'd already replied to this.  Maybe we had another thread going somewhere else?  If you've already seen this before, please ignore me repeating myself :-)

> Well, you could lazy-load everything, including the constants.

I'd be happy to consider your PR that rearchitects luaposix to do that ;-)

> Have you profiled this slowdown? Because your M1 Mac is 30+ times slower than my first generation single core Raspberry Pi model B with 256MB of RAM.

I did profile my M1 mac given your numbers above, and it turns out that macOS wastes an unreasonable amount of time doing something with dynamic library symbols on first load.  The numbers I pasted earlier are for that first load, where macOS is walking the symbol tables for all submodules, calculating address offsets and caching them for future loads which are subsequently very fast.  Of course, most of the time when I load luaposix modules, it's just after I've rebuilt them with a change, so I nearly always get the unreasonably slow first load times.  Would be nice if Apple could find a way to amortize that cost somehow?  Maybe returning from the dlopen call immediately, and either walking the symbol tables in a separate kernel thread in parallel, or caching addresses for future use on first reference.  Anyway, that day is not today, so I'll get to live with that weirdness for the forseeable future!

```
$ luarocks make --force
...
luaposix git-1 is now installed in /usr/local (license: MIT/X11)

$ command time -p lua -e "local posix = require 'posix' ; print (posix)"
table: 0x6000031402c0
real 5.94
user 0.03
sys 0.02

$ command time -p lua -e "local posix = require 'posix' ; print (posix)"
table: 0x600003c61a80
real 0.04
user 0.01
sys 0.01
```

**Comment by parke** [comment]
> Ugh, I could have sworn I'd already replied to this. Maybe we had another thread going somewhere else?

Our other threads are all older than this thread.  So your response is new info for me.

> I'd be happy to consider your PR that rearchitects luaposix to do that ;-)

Thanks for the offer.  My current strategy is the below, which is working fine, so I am unlikely to invest time implementing improvements.

```
pcall ( require, 'posix.fcntl'    )    -----------------  require  posix.fcntl
pcall ( require, 'posix.sys.stat' )    --------------  require  posix.sys.stat
pcall ( require, 'posix.unistd'   )    ----------------  require  posix.unistd
m_fcntl   =  package .loaded [ 'posix.fcntl'    ]    ----------------  m_fcntl
m_stat    =  package .loaded [ 'posix.sys.stat' ]    -----------------  m_stat
m_unistd  =  package .loaded [ 'posix.unistd'   ]    ---------------  m_unistd
```
> I did profile my M1 mac given your numbers above, and it turns out that macOS wastes an unreasonable amount of time doing something with dynamic library symbols on first load.

Fascinating.

> ... so I'll get to live with that weirdness for the forseeable future!

Alternatively, you could develop first in a Linux (or FreeBSD) VM.  And only compile on macOS once everything is working in Linux.  (I think Linux can run in a VM on an M1 Mac.)  This may or may not be worthwhile, depending on how frequently you want to recompile and test the result.
