### ISSUE TITLE
getgrgid/getgrnam/getpwuid/getpwnam don't return error messages

### ISSUE THREAD

**Issue by madchrist** [luaposix/luaposix#371]
The doc says that, on error, these functions return "nil, error message, errnum", but in practice they just return "nil"

> p = require("posix.grp") print(p.getgrnam("missing"))
> nil 
> p = require("posix.pwd") print(p.getpwnam("missing"))
> nil

**Comment by madchrist** [comment]
If nil is supposed to be the correct return value for a missing group/user, the doc should list it as a third possible return variant, distinct from the error one

**Comment by gvvaughan** [comment]
From https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwnam.html

Hi Christophe,

> A null pointer shall be returned if the requested entry is not found, or an error occurs. If the requested entry was not found, errno shall not be changed. On error, errno shall be set to indicate the error.

`errno` is not set for a missing entry nor is there a strerror() result, so the last two return values are not set, as described in the upstream documentation.  And likewise for https://pubs.opengroup.org/onlinepubs/9699919799/functions/getgrnam.html

I'm happy to merge a PR if you'd like to make the docs more explicit though.  Please make sure to audit all the APIs wrapped in all modules you amend for similar issues implied by the linked SUSv4 pages, and make the same changes wherever applicable so that the documentation remains consistent.

Cheers!
